# ===== 작업일지 클라우드 서버 (초기화 수정본) =====
import os
from datetime import datetime, date, timedelta
from flask import Flask, request, jsonify, render_template_string
import psycopg
from psycopg.rows import dict_row

app = Flask(__name__)
DATABASE_URL = os.environ.get("DATABASE_URL", "")
SEASON_START_MONTH = 3
_TFS = "☆"
_TRS = "§"

def db_conn():
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)

def parse_float_safe(s, default=0.0):
    try:
        return float(str(s).replace(",", "").strip())
    except Exception:
        return default

def parse_int_safe(s, default=0):
    try:
        return int(float(str(s).replace(",", "").strip()))
    except Exception:
        return default

def compute_wage_from_detail(detail_str):
    if not detail_str:
        return 0
    total = 0
    for part in str(detail_str).split(";"):
        if not part.strip():
            continue
        try:
            _, cnt, pay, _ = part.split("|")
            total += int(float(pay)) * int(float(cnt))
        except Exception:
            pass
    return total

def parse_task_list(text):
    if not text or not str(text).strip():
        return []
    result = []
    for rec in str(text).split(_TRS):
        rec = rec.strip()
        if not rec:
            continue
        p = rec.split(_TFS)
        while len(p) < 12:
            p.append("")
        result.append({
            "날짜": p[0], "종료날짜": p[1], "작물": p[2], "작업내용": p[3],
            "시작시간": p[4], "종료시간": p[5], "작업시간": p[6], "사용기계": p[7],
            "사용자재": p[8], "병충해": p[9], "인력내역": p[10], "비고": p[11],
        })
    return result

def serialize_task_list(task_list):
    recs = []
    for t in task_list:
        recs.append(_TFS.join([
            str(t.get("날짜","")), str(t.get("종료날짜","")), str(t.get("작물","")), str(t.get("작업내용","")),
            str(t.get("시작시간","")), str(t.get("종료시간","")), str(t.get("작업시간","")), str(t.get("사용기계","")),
            str(t.get("사용자재","")), str(t.get("병충해","")), str(t.get("인력내역","")), str(t.get("비고","")),
        ]))
    return _TRS.join(recs)

def row_to_dict(row):
    return dict(row) if row else {}

def ensure_default_options(cur):
    defaults = {
        "옵션_날씨": ["맑음","흐림","비","눈","바람","기타"],
        "옵션_작물": ["한라봉","천혜향","유라조생","극조생"],
        "옵션_작업내용": ["물관리","방제작업","전정","비료주기","수확","기타"],
        "옵션_기계": ["수동방제기","양수기","SS기","예초기","기타","사용안함"],
        "옵션_단위": ["개","병","통","포","kg","g","L","ml","말"],
    }
    for tbl, items in defaults.items():
        for item in items:
            cur.execute(f'INSERT INTO "{tbl}" ("항목") VALUES (%s) ON CONFLICT ("항목") DO NOTHING', (item,))

def init_db():
    conn = db_conn()
    cur = conn.cursor()
    cur.execute("""
    CREATE TABLE IF NOT EXISTS "작업일지" (
        "번호" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "날짜" TEXT,
        "종료날짜" TEXT,
        "날씨" TEXT,
        "작물" TEXT,
        "작업내용" TEXT,
        "인건비" INTEGER DEFAULT 0,
        "남자수" INTEGER DEFAULT 0,
        "남자단가" INTEGER DEFAULT 0,
        "여자수" INTEGER DEFAULT 0,
        "여자단가" INTEGER DEFAULT 0,
        "기타수" INTEGER DEFAULT 0,
        "기타단가" INTEGER DEFAULT 0,
        "시작시간" TEXT,
        "종료시간" TEXT,
        "작업시간" REAL DEFAULT 0,
        "사용기계" TEXT,
        "사용자재" TEXT,
        "적용병충해" TEXT,
        "비고" TEXT,
        "생성시각" TEXT,
        "수정시각" TEXT,
        "인력내역" TEXT,
        "작업목록" TEXT
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS "자재" (
        "자재명" TEXT PRIMARY KEY,
        "단위" TEXT,
        "가격" NUMERIC DEFAULT 0,
        "재고" NUMERIC DEFAULT 0
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS "병충해" (
        "이름" TEXT PRIMARY KEY,
        "권장약제" TEXT,
        "증상" TEXT
    )
    """)
    for tbl in ("옵션_날씨","옵션_작물","옵션_작업내용","옵션_기계","옵션_단위"):
        cur.execute(f'CREATE TABLE IF NOT EXISTS "{tbl}" ("항목" TEXT PRIMARY KEY)')
    ensure_default_options(cur)
    conn.commit()
    cur.close()
    conn.close()

if DATABASE_URL:
    try:
        init_db()
        print("✅ DB 초기화 완료")
    except Exception as e:
        print("DB init error:", e)

@app.route("/api/options", methods=["GET"])
def api_options():
    conn = db_conn()
    cur = conn.cursor()
    opts = {}
    for tbl in ("옵션_날씨","옵션_작물","옵션_작업내용","옵션_기계","옵션_단위"):
        cur.execute(f'SELECT "항목" FROM "{tbl}" ORDER BY "항목"')
        opts[tbl] = [r["항목"] for r in cur.fetchall()]
    cur.execute('SELECT "자재명","단위","가격","재고" FROM "자재" ORDER BY "자재명"')
    opts["자재"] = [{"name":r["자재명"],"unit":r["단위"],"price":float(r["가격"] or 0),"stock":float(r["재고"] or 0)} for r in cur.fetchall()]
    cur.execute('SELECT "이름" FROM "병충해" ORDER BY "이름"')
    opts["병충해"] = [r["이름"] for r in cur.fetchall()]
    cur.close()
    conn.close()
    return jsonify(opts)

@app.route("/api/options/<path:tbl>", methods=["POST"])
def api_add_option(tbl):
    allowed = {"옵션_날씨","옵션_작물","옵션_작업내용","옵션_기계","옵션_단위"}
    if tbl not in allowed:
        return jsonify({"ok":False}), 400
    data = request.json or {}
    value = (data.get("항목") or "").strip()
    if not value:
        return jsonify({"ok":False}), 400
    conn = db_conn()
    cur = conn.cursor()
    cur.execute(f'INSERT INTO "{tbl}" ("항목") VALUES (%s) ON CONFLICT ("항목") DO NOTHING', (value,))
    conn.commit()
    cur.close()
    conn.close()
    return jsonify({"ok":True})

@app.route("/api/options/<path:tbl>/<path:value>", methods=["DELETE"])
def api_delete_option(tbl, value):
    allowed = {"옵션_날씨","옵션_작물","옵션_작업내용","옵션_기계","옵션_단위"}
    if tbl not in allowed:
        return jsonify({"ok":False}), 400
    conn = db_conn()
    cur = conn.cursor()
    cur.execute(f'DELETE FROM "{tbl}" WHERE "항목"=%s', (value,))
    conn.commit()
    cur.close()
    conn.close()
    return jsonify({"ok":True})

@app.route("/api/pests", methods=["GET"])
def api_get_pests():
    conn = db_conn()
    cur = conn.cursor()
    cur.execute('SELECT "이름","권장약제","증상" FROM "병충해" ORDER BY "이름"')
    rows = [dict(r) for r in cur.fetchall()]
    cur.close()
    conn.close()
    return jsonify(rows)

@app.route("/api/pests", methods=["POST"])
def api_add_pest():
    data = request.json or {}
    name = (data.get("이름") or "").strip()
    if not name:
        return jsonify({"ok":False}), 400
    conn = db_conn()
    cur = conn.cursor()
    cur.execute("""
        INSERT INTO "병충해" ("이름","권장약제","증상")
        VALUES (%s,%s,%s)
        ON CONFLICT ("이름") DO UPDATE
        SET "권장약제"=EXCLUDED."권장약제","증상"=EXCLUDED."증상"
    """, (name, data.get("권장약제",""), data.get("증상","")))
    conn.commit()
    cur.close()
    conn.close()
    return jsonify({"ok":True})

@app.route("/api/pests/<path:name>", methods=["DELETE"])
def api_delete_pest(name):
    conn = db_conn()
    cur = conn.cursor()
    cur.execute('DELETE FROM "병충해" WHERE "이름"=%s', (name,))
    conn.commit()
    cur.close()
    conn.close()
    return jsonify({"ok":True})

@app.route("/api/materials", methods=["GET"])
def api_get_materials():
    conn = db_conn()
    cur = conn.cursor()
    cur.execute('SELECT "자재명","단위","가격","재고" FROM "자재" ORDER BY "자재명"')
    rows = [dict(r) for r in cur.fetchall()]
    cur.close()
    conn.close()
    return jsonify(rows)

@app.route("/api/materials", methods=["POST"])
def api_add_material():
    data = request.json or {}
    name = (data.get("자재명") or "").strip()
    if not name:
        return jsonify({"ok":False}), 400
    conn = db_conn()
    cur = conn.cursor()
    cur.execute("""
        INSERT INTO "자재" ("자재명","단위","가격","재고")
        VALUES (%s,%s,%s,%s)
        ON CONFLICT ("자재명") DO UPDATE
        SET "단위"=EXCLUDED."단위","가격"=EXCLUDED."가격","재고"=EXCLUDED."재고"
    """, (name, data.get("단위",""), parse_float_safe(data.get("가격",0)), parse_float_safe(data.get("재고",0))))
    conn.commit()
    cur.close()
    conn.close()
    return jsonify({"ok":True})

@app.route("/api/materials/<path:name>", methods=["PUT"])
def api_update_material(name):
    data = request.json or {}
    conn = db_conn()
    cur = conn.cursor()
    cur.execute('UPDATE "자재" SET "단위"=%s,"가격"=%s,"재고"=%s WHERE "자재명"=%s',
                (data.get("단위",""), parse_float_safe(data.get("가격",0)), parse_float_safe(data.get("재고",0)), name))
    conn.commit()
    cur.close()
    conn.close()
    return jsonify({"ok":True})

@app.route("/api/materials/<path:name>", methods=["DELETE"])
def api_delete_material(name):
    conn = db_conn()
    cur = conn.cursor()
    cur.execute('DELETE FROM "자재" WHERE "자재명"=%s', (name,))
    conn.commit()
    cur.close()
    conn.close()
    return jsonify({"ok":True})

@app.route("/api/works", methods=["GET"])
def api_get_works():
    q = request.args.get("q", "").strip()
    limit = int(request.args.get("limit", 80))
    conn = db_conn()
    cur = conn.cursor()
    if q:
        cur.execute("""
            SELECT "번호","날짜","종료날짜","날씨","작물","작업내용","인건비","작업시간",
                   "사용기계","사용자재","적용병충해","비고","인력내역","시작시간","종료시간",
                   COALESCE("작업목록",'') AS "작업목록"
            FROM "작업일지"
            WHERE "날짜" LIKE %s OR "작물" LIKE %s OR "작업내용" LIKE %s OR "사용자재" LIKE %s
            ORDER BY "날짜" DESC, "번호" DESC LIMIT %s
        """, (f"%{q}%", f"%{q}%", f"%{q}%", f"%{q}%", limit))
    else:
        cur.execute("""
            SELECT "번호","날짜","종료날짜","날씨","작물","작업내용","인건비","작업시간",
                   "사용기계","사용자재","적용병충해","비고","인력내역","시작시간","종료시간",
                   COALESCE("작업목록",'') AS "작업목록"
            FROM "작업일지"
            ORDER BY "날짜" DESC, "번호" DESC LIMIT %s
        """, (limit,))
    rows = [row_to_dict(r) for r in cur.fetchall()]
    for r in rows:
        r["task_items"] = parse_task_list(r.get("작업목록",""))
        r["인건비_표시"] = f"{compute_wage_from_detail(r.get('인력내역','') or ''):,}원"
    cur.close()
    conn.close()
    return jsonify(rows)

@app.route("/api/works", methods=["POST"])
def api_add_work():
    data = request.json or {}
    task_list = data.get("task_items", [])
    task_list_str = serialize_task_list(task_list) if task_list else ""
    all_crops, all_task_names, dates, end_dates, all_wages = [], [], [], [], []
    mat_agg, all_pests = {}, []
    for t in task_list:
        for c in str(t.get("작물","")).split(","):
            c = c.strip()
            if c and c not in all_crops:
                all_crops.append(c)
        if t.get("작업내용"):
            all_task_names.append(t["작업내용"])
        try:
            dates.append(date.fromisoformat(t.get("날짜","")))
        except Exception:
            pass
        try:
            end_dates.append(date.fromisoformat(t.get("종료날짜","") or t.get("날짜","")))
        except Exception:
            pass
        for part in str(t.get("사용자재","")).split(";"):
            if not part.strip():
                continue
            pp = part.split("|")
            if len(pp) == 3:
                n, q, u = pp[0], parse_float_safe(pp[1]), pp[2]
                if n:
                    mat_agg[n] = (mat_agg[n][0] + q, u) if n in mat_agg else (q, u)
        for p in str(t.get("병충해","")).split(","):
            p = p.strip()
            if p and p not in all_pests:
                all_pests.append(p)
        for part in str(t.get("인력내역","")).split(";"):
            if part.strip():
                all_wages.append(part.strip())
    rep_start = min(dates).isoformat() if dates else date.today().isoformat()
    rep_end = max(end_dates).isoformat() if end_dates else rep_start
    rep_mats = ";".join(f"{n}|{q}|{u}" for n,(q,u) in mat_agg.items())
    rep_wage = ";".join(all_wages)
    now_str = datetime.now().isoformat(timespec="seconds")
    conn = db_conn()
    cur = conn.cursor()
    for name, (qty, _) in mat_agg.items():
        cur.execute('UPDATE "자재" SET "재고" = COALESCE("재고",0) - %s WHERE "자재명"=%s', (qty, name))
    cur.execute("""
        INSERT INTO "작업일지" (
            "날짜","종료날짜","날씨","작물","작업내용","인건비",
            "남자수","남자단가","여자수","여자단가","기타수","기타단가",
            "시작시간","종료시간","작업시간","사용기계","사용자재","적용병충해","비고",
            "생성시각","수정시각","인력내역","작업목록"
        )
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        RETURNING "번호"
    """, (
        rep_start, rep_end, data.get("날씨",""), ",".join(all_crops), ", ".join(all_task_names), compute_wage_from_detail(rep_wage),
        0,0,0,0,0,0,
        task_list[0].get("시작시간","") if task_list else "",
        task_list[-1].get("종료시간","") if task_list else "",
        sum(parse_float_safe(t.get("작업시간","0")) for t in task_list),
        ", ".join(dict.fromkeys(t.get("사용기계","") for t in task_list if t.get("사용기계"))),
        rep_mats, ",".join(all_pests), "", now_str, now_str, rep_wage, task_list_str
    ))
    new_id = cur.fetchone()["번호"]
    conn.commit()
    cur.close()
    conn.close()
    return jsonify({"ok":True, "번호":new_id})

@app.route("/api/works/<int:no>", methods=["DELETE"])
def api_delete_work(no):
    conn = db_conn()
    cur = conn.cursor()
    cur.execute('DELETE FROM "작업일지" WHERE "번호"=%s', (no,))
    conn.commit()
    cur.close()
    conn.close()
    return jsonify({"ok":True})

@app.route("/api/calendar/<int:year>/<int:month>", methods=["GET"])
def api_calendar(year, month):
    import calendar as _cal
    month_start = date(year, month, 1)
    last_day = _cal.monthrange(year, month)[1]
    month_end = date(year, month, last_day)
    ms, me = month_start.isoformat(), month_end.isoformat()
    conn = db_conn()
    cur = conn.cursor()
    cur.execute("""
        SELECT "번호","날짜","종료날짜","작물","작업내용","날씨","인건비", COALESCE("작업목록",'') AS "작업목록"
        FROM "작업일지"
        WHERE "날짜" <= %s AND COALESCE("종료날짜","날짜") >= %s
        ORDER BY "날짜","번호"
    """, (me, ms))
    rows = cur.fetchall()
    day_map = {}
    for row in rows:
        row = dict(row)
        row["task_items"] = parse_task_list(row.get("작업목록",""))
        try:
            sd = date.fromisoformat(row["날짜"])
            ed = date.fromisoformat(row["종료날짜"]) if row.get("종료날짜") else sd
        except Exception:
            continue
        cur_d = max(sd, month_start)
        end_d = min(ed, month_end)
        while cur_d <= end_d:
            day_map.setdefault(str(cur_d.day), []).append(row)
            cur_d += timedelta(days=1)
    cur.close()
    conn.close()
    return jsonify({"year":year, "month":month, "days":last_day, "day_map":day_map})

@app.route("/api/stats", methods=["GET"])
def api_stats():
    y = int(request.args.get("year", date.today().year))
    m = int(request.args.get("month", date.today().month))
    import calendar as _cal
    ms = date(y, m, 1).isoformat()
    me = date(y, m, _cal.monthrange(y, m)[1]).isoformat()
    if m >= SEASON_START_MONTH:
        ss = date(y, SEASON_START_MONTH, 1).isoformat()
        se = (date(y+1, SEASON_START_MONTH, 1)-timedelta(days=1)).isoformat()
    else:
        ss = date(y-1, SEASON_START_MONTH, 1).isoformat()
        se = (date(y, SEASON_START_MONTH, 1)-timedelta(days=1)).isoformat()
    conn = db_conn()
    cur = conn.cursor()
    def calc(s, e):
        cur.execute('SELECT COALESCE(SUM("인건비"),0) AS "합계", COUNT(*) AS "건수" FROM "작업일지" WHERE "날짜" BETWEEN %s AND %s', (s,e))
        r = cur.fetchone() or {}
        return {"인건비": r.get("합계",0) or 0, "건수": r.get("건수",0) or 0}
    month_stat = calc(ms, me)
    season_stat = calc(ss, se)
    cur.close()
    conn.close()
    return jsonify({"당월":month_stat, "시즌":season_stat})

HTML = """<!DOCTYPE html>
<html lang='ko'>
<head>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
<title>작업일지</title>
<style>
:root{--green:#2d6a4f;--green2:#40916c;--green3:#74c69d;--bg:#f0f7f4;--card:#fff;--text:#1b2e25;--gray:#6c757d;--border:#d8ead3;--accent:#e9f5e1;--red:#c62828;--blue:#1565c0}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Noto Sans KR',sans-serif;background:var(--bg);color:var(--text);min-height:100vh}
.page{display:none;padding:16px 12px 86px;max-width:700px;margin:0 auto}.page.active{display:block}
.page-header{font-size:20px;font-weight:700;color:var(--green);margin-bottom:14px}
.card,.form-section,.stat-box{background:var(--card);border-radius:14px;padding:14px;margin-bottom:10px;box-shadow:0 1px 6px rgba(0,0,0,.07)}
.card{border-left:4px solid var(--green3)}
.card-date{font-size:13px;color:var(--gray);margin-bottom:4px}.card-title{font-size:16px;font-weight:700;color:var(--green);margin-bottom:6px}
.card-row{font-size:13px;color:#444;margin:2px 0;display:flex;gap:6px}.card-row span{color:var(--gray);min-width:50px;font-size:12px}
.tag{display:inline-block;background:var(--accent);color:var(--green2);border-radius:20px;padding:2px 9px;font-size:11px;margin:2px 2px 0 0}
.search-box,.row2,.row3,.toolbar{display:flex;gap:8px}.row2>*{flex:1}.row3>*{flex:1}
input,select,textarea,button{font:inherit}input,select,textarea{width:100%;border:1.5px solid var(--border);border-radius:9px;padding:10px 12px;background:#fff;color:var(--text)}
textarea{resize:vertical;min-height:64px}.form-row{margin-bottom:12px}.form-row label{display:block;font-size:12px;color:var(--gray);margin-bottom:4px;font-weight:600}
.btn{border:none;border-radius:10px;padding:10px 14px;cursor:pointer;font-weight:700}.btn-primary{background:var(--green2);color:#fff}.btn-secondary{background:var(--accent);color:var(--green);border:1px solid var(--border)}.btn-danger{background:#fde8e8;color:var(--red)}.btn-small{padding:6px 10px;font-size:12px}
.tab-bar{position:fixed;left:0;right:0;bottom:0;background:#fff;border-top:1px solid var(--border);display:flex;z-index:100;box-shadow:0 -2px 10px rgba(0,0,0,.08)}
.tab-btn{flex:1;border:none;background:none;padding:8px 4px;font-size:11px;color:var(--gray);display:flex;flex-direction:column;align-items:center;gap:3px;cursor:pointer}.tab-btn .ico{font-size:20px}.tab-btn.active{color:var(--green2)}
.stats-bar{display:flex;gap:8px;margin-bottom:12px}.stat-box{flex:1;text-align:center}.stat-box .sv{font-size:16px;font-weight:700;color:var(--green)}.stat-box .sl{font-size:11px;color:var(--gray);margin-top:2px}
.cal-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:3px}.cal-head{text-align:center;font-size:11px;color:var(--gray);padding:4px 0;font-weight:600}.cal-day{min-height:64px;background:#fff;border-radius:8px;padding:4px;position:relative;cursor:pointer}.cal-day.today{background:#e8f5e9;border:2px solid var(--green3)}.cal-day.empty{background:none}.cal-day .dn{font-size:12px;font-weight:600;text-align:right}.cal-event{font-size:9px;background:var(--green3);color:#fff;border-radius:3px;padding:1px 3px;margin-top:1px;white-space:nowrap;overflow:hidden}
.chip-group{display:flex;flex-wrap:wrap;gap:6px;margin-top:4px}.chip{background:var(--accent);border:1.5px solid var(--border);border-radius:20px;padding:5px 13px;font-size:13px;cursor:pointer}.chip.selected{background:var(--green2);color:#fff;border-color:var(--green2)}
.task-item{background:var(--accent);border-radius:10px;padding:12px;margin-bottom:8px;border-left:3px solid var(--green2)}
.list-row{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:10px 0;border-bottom:1px solid #eef4ef}.list-row:last-child{border-bottom:none}.muted{color:var(--gray);font-size:12px}
.modal-bg{position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:200;display:none;align-items:flex-end}.modal-bg.open{display:flex}.modal{background:#fff;border-radius:20px 20px 0 0;width:100%;max-height:90vh;overflow-y:auto;padding:20px 16px 40px}.modal-title{font-size:17px;font-weight:700;color:var(--green);margin-bottom:16px}.empty{text-align:center;padding:40px 20px;color:var(--gray)}
</style>
</head>
<body>
<div class='page active' id='page-works'>
  <div class='page-header'>📋 작업일지</div>
  <div class='search-box' style='margin-bottom:14px;'>
    <input id='search-input' type='text' placeholder='날짜·작물·작업내용·자재 검색...'>
    <button class='btn btn-primary' onclick='loadWorks()'>검색</button>
  </div>
  <div id='works-list'><div class='empty'>불러오는 중...</div></div>
</div>
<div class='page' id='page-calendar'>
  <div class='page-header'>📅 작업달력</div>
  <div class='toolbar' style='margin-bottom:10px;'>
    <select id='cal-year' onchange='loadCalendarAndStats()'></select>
    <select id='cal-month' onchange='loadCalendarAndStats()'></select>
    <button class='btn btn-secondary' onclick='goToday()'>오늘</button>
  </div>
  <div class='stats-bar'>
    <div class='stat-box'><div class='sv' id='stat-month-wage'>-</div><div class='sl'>당월 인건비</div></div>
    <div class='stat-box'><div class='sv' id='stat-season-wage'>-</div><div class='sl'>시즌 인건비</div></div>
    <div class='stat-box'><div class='sv' id='stat-month-cnt'>-</div><div class='sl'>당월 건수</div></div>
  </div>
  <div class='cal-grid' id='cal-grid'></div>
</div>
<div class='page' id='page-add'>
  <div class='page-header'>✏️ 작업 입력</div>
  <div class='form-section'><div class='form-row'><label>날씨</label><select id='f-weather'></select></div></div>
  <div class='form-section'><h3 style='margin-bottom:12px;color:var(--green2)'>🌿 작업 목록</h3><div id='task-items-container'></div><button class='btn btn-secondary' onclick='openTaskModal()'>➕ 작업 추가</button></div>
  <button class='btn btn-primary' style='width:100%' onclick='submitWork()'>💾 저장</button>
</div>
<div class='page' id='page-materials'>
  <div class='page-header'>📦 자재관리</div>
  <div class='form-section'>
    <div class='row3'><div class='form-row'><label>자재명</label><input id='mat-name'></div><div class='form-row'><label>단위</label><input id='mat-unit' placeholder='예: 병'></div><div class='form-row'><label>가격</label><input id='mat-price' type='number' value='0'></div></div>
    <div class='row2'><div class='form-row'><label>재고</label><input id='mat-stock' type='number' step='0.1' value='0'></div><div class='form-row' style='align-self:end;'><button class='btn btn-primary' style='width:100%' onclick='saveMaterial()'>저장</button></div></div>
  </div>
  <div class='card'><div id='materials-list'></div></div>
</div>
<div class='page' id='page-options'>
  <div class='page-header'>⚙️ 옵션관리</div>
  <div class='form-section'><h3 style='margin-bottom:12px;color:var(--green2)'>🌤 날씨</h3><div class='row2'><input id='opt-weather' placeholder='날씨 추가'><button class='btn btn-primary' onclick="addOption('옵션_날씨','opt-weather')">추가</button></div><div id='list-weather' style='margin-top:10px;'></div></div>
  <div class='form-section'><h3 style='margin-bottom:12px;color:var(--green2)'>🌱 작물</h3><div class='row2'><input id='opt-crop' placeholder='작물 추가'><button class='btn btn-primary' onclick="addOption('옵션_작물','opt-crop')">추가</button></div><div id='list-crop' style='margin-top:10px;'></div></div>
  <div class='form-section'><h3 style='margin-bottom:12px;color:var(--green2)'>🧰 작업내용</h3><div class='row2'><input id='opt-task' placeholder='작업내용 추가'><button class='btn btn-primary' onclick="addOption('옵션_작업내용','opt-task')">추가</button></div><div id='list-task' style='margin-top:10px;'></div></div>
  <div class='form-section'><h3 style='margin-bottom:12px;color:var(--green2)'>🔧 기계</h3><div class='row2'><input id='opt-machine' placeholder='기계 추가'><button class='btn btn-primary' onclick="addOption('옵션_기계','opt-machine')">추가</button></div><div id='list-machine' style='margin-top:10px;'></div></div>
  <div class='form-section'><h3 style='margin-bottom:12px;color:var(--green2)'>🦟 병충해</h3><div class='row3'><input id='pest-name' placeholder='이름'><input id='pest-drug' placeholder='권장약제'><input id='pest-symptom' placeholder='증상'></div><button class='btn btn-primary' style='margin-top:8px;' onclick='savePest()'>병충해 추가</button><div id='list-pests' style='margin-top:10px;'></div></div>
</div>
<div class='tab-bar'>
  <button class='tab-btn active' onclick="showTab('works')" id='tab-works'><span class='ico'>📋</span>작업일지</button>
  <button class='tab-btn' onclick="showTab('calendar')" id='tab-calendar'><span class='ico'>📅</span>달력</button>
  <button class='tab-btn' onclick="showTab('add')" id='tab-add'><span class='ico'>✏️</span>입력</button>
  <button class='tab-btn' onclick="showTab('materials')" id='tab-materials'><span class='ico'>📦</span>자재</button>
  <button class='tab-btn' onclick="showTab('options')" id='tab-options'><span class='ico'>⚙️</span>옵션</button>
</div>
<div class='modal-bg' id='task-modal'><div class='modal'><div class='modal-title'>작업 추가</div><div class='form-row'><label>작업시작일</label><input type='date' id='tm-date'></div><div class='row2'><div class='form-row'><label>연속 일수</label><input type='number' id='tm-days' value='1' min='1' oninput='calcEndDate()'></div><div class='form-row'><label>작업종료일</label><input type='date' id='tm-end' readonly></div></div><div class='form-row'><label>작물(복수선택)</label><div class='chip-group' id='tm-crops'></div></div><div class='form-row'><label>작업내용</label><select id='tm-task'></select></div><div class='row2'><div class='form-row'><label>시작시간</label><input type='time' id='tm-start'></div><div class='form-row'><label>종료시간</label><input type='time' id='tm-end-time' oninput='calcWtime()'></div></div><div class='row2'><div class='form-row'><label>작업시간(h)</label><input type='number' id='tm-wtime' step='0.5'></div><div class='form-row'><label>사용기계</label><select id='tm-machine'></select></div></div><div class='form-row'><label>사용자재</label><div id='tm-mats-chips' class='chip-group'></div><div id='tm-selected-mats' style='margin-top:6px;'></div></div><div class='form-row'><label>병충해</label><div class='chip-group' id='tm-pests'></div></div><div class='form-row'><label>인력(성별/인원/단가)</label><div id='tm-wages'></div><button class='btn btn-secondary' style='margin-top:6px;' onclick='addWage()'>+ 인력 추가</button></div><div class='form-row'><label>비고</label><textarea id='tm-note'></textarea></div><button class='btn btn-primary' style='width:100%' onclick='confirmTask()'>작업 추가</button><button class='btn btn-secondary' style='width:100%;margin-top:8px;' onclick='closeTaskModal()'>취소</button></div></div>
<div class='modal-bg' id='cal-modal'><div class='modal'><div class='modal-title' id='cal-modal-title'></div><div id='cal-modal-body'></div><button class='btn btn-secondary' style='width:100%;margin-top:8px;' onclick="document.getElementById('cal-modal').classList.remove('open')">닫기</button></div></div>
<script>
let OPTIONS = {}, TASKS = [], calYear = new Date().getFullYear(), calMonth = new Date().getMonth()+1, editingMaterial = null;
function escapeJs(str){ return String(str).replace(/\\/g,'\\\\').replace(/'/g,"\\'"); }
function showTab(t){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.getElementById('page-'+t).classList.add('active');document.getElementById('tab-'+t).classList.add('active');if(t==='works') loadWorks();if(t==='calendar') loadCalendarAndStats();if(t==='materials') loadMaterials();if(t==='options') loadOptionsManage();}
function buildYearMonthSelects(){const ySel=document.getElementById('cal-year');const mSel=document.getElementById('cal-month');const cy=new Date().getFullYear();ySel.innerHTML='';for(let y=cy-5;y<=cy+1;y++) ySel.innerHTML += `<option value="${y}">${y}년</option>`;mSel.innerHTML='';for(let m=1;m<=12;m++) mSel.innerHTML += `<option value="${m}">${m}월</option>`;ySel.value=calYear;mSel.value=calMonth;}
function goToday(){const d=new Date();calYear=d.getFullYear();calMonth=d.getMonth()+1;document.getElementById('cal-year').value=calYear;document.getElementById('cal-month').value=calMonth;loadCalendarAndStats();}
async function loadOptions(){const r=await fetch('/api/options');OPTIONS=await r.json();document.getElementById('f-weather').innerHTML=(OPTIONS['옵션_날씨']||[]).map(v=>`<option>${v}</option>`).join('');document.getElementById('tm-task').innerHTML=(OPTIONS['옵션_작업내용']||[]).map(v=>`<option>${v}</option>`).join('');document.getElementById('tm-machine').innerHTML=(OPTIONS['옵션_기계']||[]).map(v=>`<option>${v}</option>`).join('');document.getElementById('tm-crops').innerHTML=(OPTIONS['옵션_작물']||[]).map(v=>`<span class="chip" onclick="toggleChip(this)">${v}</span>`).join('');document.getElementById('tm-mats-chips').innerHTML=(OPTIONS['자재']||[]).map(m=>`<span class="chip" onclick="addMat('${escapeJs(m.name)}','${escapeJs(m.unit||'')}')">${m.name}(${m.unit||''})</span>`).join('');document.getElementById('tm-pests').innerHTML=(OPTIONS['병충해']||[]).map(p=>`<span class="chip" onclick="toggleChip(this)">${p}</span>`).join('');}
async function loadWorks(){const q=document.getElementById('search-input').value.trim();const r=await fetch(`/api/works?q=${encodeURIComponent(q)}&limit=80`);const data=await r.json();const el=document.getElementById('works-list');if(!data.length){el.innerHTML='<div class="empty">작업 내역이 없습니다.</div>';return;}el.innerHTML=data.map(w=>{const items=w.task_items||[];let body='';if(items.length){body=items.map(t=>`<div class="task-item" style="margin:4px 0;padding:8px;font-size:12px;"><b style="color:var(--green)">${t.작업내용||''}</b>${t.작물?`<span class="tag">${t.작물}</span>`:''}${t.날짜?`<div class="muted">📅 ${t.날짜}${t.종료날짜&&t.종료날짜!==t.날짜?' ~ '+t.종료날짜:''}</div>`:''}${t.시작시간||t.종료시간?`<div class="muted">⏰ ${t.시작시간} ~ ${t.종료시간} (${t.작업시간}h)</div>`:''}${t.사용기계?`<div class="muted">🔧 ${t.사용기계}</div>`:''}${t.사용자재?`<div class="muted">🪣 ${t.사용자재.split(';').filter(Boolean).map(p=>p.split('|')[0]).join(', ')}</div>`:''}${t.병충해?`<div class="muted">🦟 ${t.병충해}</div>`:''}${t.인력내역?`<div class="muted">👷 ${formatWage(t.인력내역)}</div>`:''}</div>`).join('')}else{body=`<div class="card-row"><span>작물</span>${w.작물||'-'}</div><div class="card-row"><span>시간</span>${w.시작시간||''} ~ ${w.종료시간||''}</div><div class="card-row"><span>기계</span>${w.사용기계||'-'}</div>`;}const dateLabel=w.종료날짜&&w.종료날짜!==w.날짜?`${w.날짜} ~ ${w.종료날짜}`:(w.날짜||'');return `<div class="card"><div class="card-date">📅 ${dateLabel} ☀️ ${w.날씨||''}</div><div class="card-title">🧰 ${w.작업내용||items.map(t=>t.작업내용).join(' / ')}</div>${body}${w.인건비_표시&&w.인건비_표시!=='0원'?`<div class="card-row"><span>인건비</span><b style="color:var(--blue)">${w.인건비_표시}</b></div>`:''}<div style="margin-top:10px"><button class="btn btn-danger btn-small" onclick="deleteWork(${w.번호})">삭제</button></div></div>`;}).join('');}
function formatWage(str){return (str||'').split(';').filter(Boolean).map(p=>{const pp=p.split('|');if(pp.length>=3) return `${pp[0]} ${pp[1]}명×${parseInt(pp[2]||0).toLocaleString()}원`;return p;}).join(', ');}
async function deleteWork(no){if(!confirm('이 작업을 삭제할까요?')) return;await fetch(`/api/works/${no}`, {method:'DELETE'});await loadWorks();await loadMaterials();}
async function loadCalendarAndStats(){calYear=parseInt(document.getElementById('cal-year').value||calYear);calMonth=parseInt(document.getElementById('cal-month').value||calMonth);await Promise.all([loadStats(), loadCalendar()]);}
async function loadStats(){const r=await fetch(`/api/stats?year=${calYear}&month=${calMonth}`);const d=await r.json();document.getElementById('stat-month-wage').textContent=(d.당월.인건비||0).toLocaleString()+'원';document.getElementById('stat-season-wage').textContent=(d.시즌.인건비||0).toLocaleString()+'원';document.getElementById('stat-month-cnt').textContent=(d.당월.건수||0)+'건';}
async function loadCalendar(){const r=await fetch(`/api/calendar/${calYear}/${calMonth}`);const d=await r.json();const DAYS=['일','월','화','수','목','금','토'];const today=new Date(),ty=today.getFullYear(),tm=today.getMonth()+1,td=today.getDate();const firstDow=new Date(calYear,calMonth-1,1).getDay();let html=DAYS.map(v=>`<div class="cal-head">${v}</div>`).join('');for(let i=0;i<firstDow;i++) html += '<div class="cal-day empty"></div>';for(let day=1; day<=d.days; day++){const isToday=ty===calYear&&tm===calMonth&&td===day;const works=d.day_map[String(day)]||[];const evHTML=works.slice(0,2).map(w=>{const items=w.task_items||[];const label=items.length?items[0].작업내용:(w.작업내용||'작업');return `<div class="cal-event">${label}</div>`;}).join('') + (works.length>2?`<div class="cal-event" style="background:#999">+${works.length-2}</div>`:'');html += `<div class="cal-day${isToday?' today':''}" onclick="showCalDay(${day})"><div class="dn">${day}</div>${evHTML}</div>`;}document.getElementById('cal-grid').innerHTML=html;window._calDayMap=d.day_map;}
function showCalDay(day){const works=(window._calDayMap||{})[String(day)]||[];if(!works.length) return;document.getElementById('cal-modal-title').textContent=`${calYear}년 ${calMonth}월 ${day}일`;document.getElementById('cal-modal-body').innerHTML=works.map(w=>{const items=w.task_items||[];let body=items.length?items.map(t=>`<div class="task-item"><b style="color:var(--green)">${t.작업내용||''}</b>${t.작물?`<span class="tag">${t.작물}</span>`:''}${t.날짜?`<div class="muted">📅 ${t.날짜}${t.종료날짜&&t.종료날짜!==t.날짜?' ~ '+t.종료날짜:''}</div>`:''}${t.시작시간?`<div class="muted">⏰ ${t.시작시간} ~ ${t.종료시간} (${t.작업시간}h)</div>`:''}${t.사용기계?`<div class="muted">🔧 ${t.사용기계}</div>`:''}${t.사용자재?`<div class="muted">🪣 ${t.사용자재.split(';').filter(Boolean).map(p=>p.split('|')[0]).join(', ')}</div>`:''}${t.병충해?`<div class="muted">🦟 ${t.병충해}</div>`:''}${t.인력내역?`<div class="muted">👷 ${formatWage(t.인력내역)}</div>`:''}</div>`).join(''):`<div>${w.작업내용||''}</div>`;return `<div class="card">${body}</div>`;}).join('');document.getElementById('cal-modal').classList.add('open');}
function toggleChip(el){ el.classList.toggle('selected'); }
function openTaskModal(){const today=new Date().toISOString().slice(0,10);document.getElementById('tm-date').value=today;document.getElementById('tm-days').value=1;document.getElementById('tm-end').value=today;document.getElementById('tm-start').value='';document.getElementById('tm-end-time').value='';document.getElementById('tm-wtime').value='';document.getElementById('tm-note').value='';document.getElementById('tm-wages').innerHTML='';document.querySelectorAll('#tm-crops .chip, #tm-pests .chip').forEach(c=>c.classList.remove('selected'));document.getElementById('tm-selected-mats').innerHTML='';document.getElementById('task-modal').classList.add('open');}
function closeTaskModal(){document.getElementById('task-modal').classList.remove('open');}
function calcEndDate(){const d=document.getElementById('tm-date').value;const n=parseInt(document.getElementById('tm-days').value)||1;if(d){const ed=new Date(d);ed.setDate(ed.getDate()+n-1);document.getElementById('tm-end').value=ed.toISOString().slice(0,10);}}
document.addEventListener('DOMContentLoaded', ()=>{document.getElementById('tm-date').addEventListener('change', calcEndDate);});
function calcWtime(){const s=document.getElementById('tm-start').value;const e=document.getElementById('tm-end-time').value;if(s&&e){const sh=s.split(':').map(Number);const eh=e.split(':').map(Number);const diff=(eh[0]*60+eh[1])-(sh[0]*60+sh[1]);if(diff>0){let v=(diff/60).toFixed(1);if(v.endsWith('.0')) v=v.slice(0,-2);document.getElementById('tm-wtime').value=v;}}}
function addMat(name, unit){const qty=prompt(`${name} 수량 (${unit}):`, '1');if(qty===null) return;const qf=parseFloat(qty);if(isNaN(qf)||qf<=0){alert('올바른 수량을 입력하세요.');return;}const cont=document.getElementById('tm-selected-mats');const id=`mat-${Date.now()}`;const div=document.createElement('div');div.id=id;div.className='list-row';div.dataset.mat=`${name}|${qf}|${unit}`;div.innerHTML=`<div>${name} ${qf}${unit}</div><button class="btn btn-danger btn-small" onclick="document.getElementById('${id}').remove()">삭제</button>`;cont.appendChild(div);}
function addWage(){const cont=document.getElementById('tm-wages');const id=`wage-${Date.now()}`;const div=document.createElement('div');div.id=id;div.className='row3';div.style.marginTop='6px';div.innerHTML=`<select><option>남자</option><option>여자</option><option>기타</option></select><input type="number" placeholder="인원" min="1" value="1"><input type="number" placeholder="단가"><input type="text" placeholder="구분"><button class="btn btn-danger btn-small" onclick="document.getElementById('${id}').remove()">삭제</button>`;cont.appendChild(div);}
function confirmTask(){const startDate=document.getElementById('tm-date').value;const endDate=document.getElementById('tm-end').value || startDate;const taskVal=document.getElementById('tm-task').value;if(!startDate||!taskVal){alert('날짜와 작업내용을 입력하세요.');return;}const crops=[...document.querySelectorAll('#tm-crops .chip.selected')].map(c=>c.textContent).join(',');const sh=document.getElementById('tm-start').value || '00:00';const eh=document.getElementById('tm-end-time').value || '00:00';const wt=document.getElementById('tm-wtime').value || '0';const mac=document.getElementById('tm-machine').value;const mats=[...document.querySelectorAll('#tm-selected-mats [data-mat]')].map(el=>el.dataset.mat).join(';');const pests=[...document.querySelectorAll('#tm-pests .chip.selected')].map(c=>c.textContent).join(',');const wages=[...document.querySelectorAll('#tm-wages > div')].map(d=>{const sel=d.querySelector('select');const inputs=d.querySelectorAll('input');if(sel&&inputs.length>=3) return `${sel.value}|${inputs[0].value}|${inputs[1].value}|${inputs[2].value||'일반'}`;return '';}).filter(Boolean).join(';');const note=document.getElementById('tm-note').value.trim();TASKS.push({날짜:startDate,종료날짜:endDate,작물:crops,작업내용:taskVal,시작시간:sh,종료시간:eh,작업시간:wt,사용기계:mac,사용자재:mats,병충해:pests,인력내역:wages,비고:note});renderTaskItems();closeTaskModal();}
function renderTaskItems(){const cont=document.getElementById('task-items-container');cont.innerHTML=TASKS.map((t,i)=>`<div class="task-item"><div style="display:flex;justify-content:space-between;gap:8px;"><div><b>${t.작업내용}</b></div><button class="btn btn-danger btn-small" onclick="TASKS.splice(${i},1);renderTaskItems()">삭제</button></div><div class="muted" style="margin-top:4px;">📅 ${t.날짜}${t.종료날짜&&t.종료날짜!==t.날짜?' ~ '+t.종료날짜:''}${t.작물?` | 🌱 ${t.작물}`:''}${t.시작시간!=='00:00'?` | ⏰ ${t.시작시간}~${t.종료시간}(${t.작업시간}h)`:''}${t.사용기계?` | 🔧 ${t.사용기계}`:''}</div></div>`).join('');}
async function submitWork(){if(!TASKS.length){alert('작업을 추가하세요.');return;}const weather=document.getElementById('f-weather').value;const payload={날씨:weather, task_items:TASKS};const r=await fetch('/api/works', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload)});const d=await r.json();if(d.ok){alert('저장됐습니다.');TASKS=[];renderTaskItems();await loadOptions();await loadMaterials();showTab('works');}else{alert('저장 실패');}}
async function loadMaterials(){const r=await fetch('/api/materials');const rows=await r.json();const el=document.getElementById('materials-list');if(!rows.length){el.innerHTML='<div class="empty">등록된 자재가 없습니다.</div>';return;}el.innerHTML='';rows.forEach(row=>{const wrap=document.createElement('div');wrap.className='list-row';const left=document.createElement('div');left.innerHTML=`<div><b>${row.자재명}</b> <span class="muted">(${row.단위||''})</span></div><div class="muted">가격: ${Number(row.가격||0).toLocaleString()} / 재고: ${Number(row.재고||0).toLocaleString()}</div>`;const right=document.createElement('div');right.style.display='flex';right.style.gap='6px';const editBtn=document.createElement('button');editBtn.className='btn btn-secondary btn-small';editBtn.textContent='수정';editBtn.onclick=()=>editMaterial(row);const delBtn=document.createElement('button');delBtn.className='btn btn-danger btn-small';delBtn.textContent='삭제';delBtn.onclick=()=>deleteMaterial(row.자재명);right.appendChild(editBtn);right.appendChild(delBtn);wrap.appendChild(left);wrap.appendChild(right);el.appendChild(wrap);});}
function editMaterial(obj){editingMaterial=obj["자재명"];document.getElementById('mat-name').value=obj["자재명"];document.getElementById('mat-unit').value=obj["단위"] || '';document.getElementById('mat-price').value=obj["가격"] || 0;document.getElementById('mat-stock').value=obj["재고"] || 0;}
async function saveMaterial(){const payload={자재명:document.getElementById('mat-name').value.trim(),단위:document.getElementById('mat-unit').value.trim(),가격:document.getElementById('mat-price').value || 0,재고:document.getElementById('mat-stock').value || 0};if(!payload.자재명){alert('자재명을 입력하세요.');return;}if(editingMaterial && editingMaterial === payload.자재명){await fetch(`/api/materials/${encodeURIComponent(editingMaterial)}`, {method:'PUT', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload)});}else{await fetch('/api/materials', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload)});}editingMaterial=null;document.getElementById('mat-name').value='';document.getElementById('mat-unit').value='';document.getElementById('mat-price').value=0;document.getElementById('mat-stock').value=0;await loadMaterials();await loadOptions();}
async function deleteMaterial(name){if(!confirm('자재를 삭제할까요?')) return;await fetch(`/api/materials/${encodeURIComponent(name)}`, {method:'DELETE'});await loadMaterials();await loadOptions();}
async function loadOptionsManage(){await loadOptions();renderOptionList('list-weather', '옵션_날씨');renderOptionList('list-crop', '옵션_작물');renderOptionList('list-task', '옵션_작업내용');renderOptionList('list-machine', '옵션_기계');await loadPestsManage();}
function renderOptionList(elId, key){const el=document.getElementById(elId);const items=OPTIONS[key] || [];if(!items.length){el.innerHTML='<div class="empty">없음</div>';return;}el.innerHTML='';items.forEach(value=>{const wrap=document.createElement('div');wrap.className='list-row';const left=document.createElement('div');left.textContent=value;const btn=document.createElement('button');btn.className='btn btn-danger btn-small';btn.textContent='삭제';btn.onclick=()=>deleteOption(key, value);wrap.appendChild(left);wrap.appendChild(btn);el.appendChild(wrap);});}
async function addOption(tbl, inputId){const value=document.getElementById(inputId).value.trim();if(!value) return;await fetch(`/api/options/${encodeURIComponent(tbl)}`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({항목:value})});document.getElementById(inputId).value='';await loadOptionsManage();}
async function deleteOption(tbl, value){if(!confirm('삭제할까요?')) return;await fetch(`/api/options/${encodeURIComponent(tbl)}/${encodeURIComponent(value)}`, {method:'DELETE'});await loadOptionsManage();}
async function loadPestsManage(){const r=await fetch('/api/pests');const items=await r.json();const el=document.getElementById('list-pests');if(!items.length){el.innerHTML='<div class="empty">없음</div>';return;}el.innerHTML='';items.forEach(p=>{const wrap=document.createElement('div');wrap.className='list-row';const left=document.createElement('div');left.innerHTML=`<div><b>${p.이름}</b></div><div class="muted">권장약제: ${p.권장약제||'-'} / 증상: ${p.증상||'-'}</div>`;const btn=document.createElement('button');btn.className='btn btn-danger btn-small';btn.textContent='삭제';btn.onclick=()=>deletePest(p.이름);wrap.appendChild(left);wrap.appendChild(btn);el.appendChild(wrap);});}
async function savePest(){const payload={이름:document.getElementById('pest-name').value.trim(),권장약제:document.getElementById('pest-drug').value.trim(),증상:document.getElementById('pest-symptom').value.trim()};if(!payload.이름){alert('병충해명을 입력하세요.');return;}await fetch('/api/pests', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload)});document.getElementById('pest-name').value='';document.getElementById('pest-drug').value='';document.getElementById('pest-symptom').value='';await loadOptionsManage();}
async function deletePest(name){if(!confirm('삭제할까요?')) return;await fetch(`/api/pests/${encodeURIComponent(name)}`, {method:'DELETE'});await loadOptionsManage();}
window.addEventListener('error', function(e){console.log("JS ERROR:", e.message);alert("화면 오류 발생: " + e.message);});
async function initApp(){try{buildYearMonthSelects();await loadOptions();await loadWorks();await loadMaterials();await loadOptionsManage();await loadCalendarAndStats();}catch(e){alert("초기화 오류: " + e.message);console.error(e);}}
initApp();
document.querySelectorAll('.modal-bg').forEach(bg=>{bg.addEventListener('click', e=>{if(e.target===bg) bg.classList.remove('open');});});
</script>
</body>
</html>"""

@app.route("/")
def index():
    return render_template_string(HTML)

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
