# ===== 작업일지 클라우드 서버 (테이블명 따옴표 수정 완성본) =====
import os
from datetime import datetime, date, timedelta
from flask import Flask, request, jsonify, render_template_string
import psycopg
from psycopg.rows import dict_row

app = Flask(__name__)
DATABASE_URL = os.environ.get("DATABASE_URL", "")
SEASON_START_MONTH = 3
_TFS = "☆"
_TRS = "§"


def db_conn():
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def parse_float_safe(s, default=0.0):
    try:
        return float(str(s).replace(",", "").strip())
    except Exception:
        return default


def compute_wage_from_detail(detail_str):
    if not detail_str:
        return 0
    total = 0
    for part in str(detail_str).split(";"):
        if not part.strip():
            continue
        try:
            _, cnt, pay, _ = part.split("|")
            total += int(float(pay)) * int(float(cnt))
        except Exception:
            pass
    return total


def parse_task_list(text):
    if not text or not str(text).strip():
        return []
    result = []
    for rec in str(text).split(_TRS):
        rec = rec.strip()
        if not rec:
            continue
        p = rec.split(_TFS)
        while len(p) < 12:
            p.append("")
        result.append({
            "날짜": p[0], "종료날짜": p[1], "작물": p[2], "작업내용": p[3],
            "시작시간": p[4], "종료시간": p[5], "작업시간": p[6], "사용기계": p[7],
            "사용자재": p[8], "병충해": p[9], "인력내역": p[10], "비고": p[11],
        })
    return result


def ensure_default_options(cur):
    defaults = {
        "옵션_날씨": ["맑음", "흐림", "비", "눈", "바람", "기타"],
        "옵션_작물": ["한라봉", "천혜향", "유라조생", "극조생"],
        "옵션_작업내용": ["물관리", "방제작업", "전정", "비료주기", "수확", "기타"],
        "옵션_기계": ["수동방제기", "양수기", "SS기", "예초기", "기타", "사용안함"],
        "옵션_단위": ["개", "병", "통", "포", "kg", "g", "L", "ml", "말"],
    }
    for tbl, items in defaults.items():
        for item in items:
            cur.execute(f'INSERT INTO "{tbl}" ("항목") VALUES (%s) ON CONFLICT ("항목") DO NOTHING', (item,))


def init_db():
    conn = db_conn()
    cur = conn.cursor()
    cur.execute('''
    CREATE TABLE IF NOT EXISTS "작업일지" (
        "번호" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "날짜" TEXT,
        "종료날짜" TEXT,
        "날씨" TEXT,
        "작물" TEXT,
        "작업내용" TEXT,
        "인건비" INTEGER DEFAULT 0,
        "남자수" INTEGER DEFAULT 0,
        "남자단가" INTEGER DEFAULT 0,
        "여자수" INTEGER DEFAULT 0,
        "여자단가" INTEGER DEFAULT 0,
        "기타수" INTEGER DEFAULT 0,
        "기타단가" INTEGER DEFAULT 0,
        "시작시간" TEXT,
        "종료시간" TEXT,
        "작업시간" REAL DEFAULT 0,
        "사용기계" TEXT,
        "사용자재" TEXT,
        "적용병충해" TEXT,
        "비고" TEXT,
        "생성시각" TEXT,
        "수정시각" TEXT,
        "인력내역" TEXT,
        "작업목록" TEXT
    )
    ''')
    cur.execute('''
    CREATE TABLE IF NOT EXISTS "자재" (
        "자재명" TEXT PRIMARY KEY,
        "단위" TEXT,
        "가격" NUMERIC DEFAULT 0,
        "재고" NUMERIC DEFAULT 0
    )
    ''')
    cur.execute('''
    CREATE TABLE IF NOT EXISTS "병충해" (
        "이름" TEXT PRIMARY KEY,
        "권장약제" TEXT,
        "증상" TEXT
    )
    ''')
    for tbl in ("옵션_날씨", "옵션_작물", "옵션_작업내용", "옵션_기계", "옵션_단위"):
        cur.execute(f'CREATE TABLE IF NOT EXISTS "{tbl}" ("항목" TEXT PRIMARY KEY)')
    ensure_default_options(cur)
    conn.commit()
    cur.close()
    conn.close()


if DATABASE_URL:
    init_db()


@app.route('/api/works')
def api_works():
    q = request.args.get('q', '').strip()
    limit = int(request.args.get('limit', 100))
    conn = db_conn()
    cur = conn.cursor()
    if q:
        cur.execute('''
            SELECT "번호","날짜","종료날짜","날씨","작물","작업내용","사용기계","사용자재",COALESCE("작업목록",'') AS "작업목록","인력내역"
            FROM "작업일지"
            WHERE "날짜" LIKE %s OR "작물" LIKE %s OR "작업내용" LIKE %s OR "사용자재" LIKE %s
            ORDER BY "날짜" DESC, "번호" DESC LIMIT %s
        ''', (f'%{q}%', f'%{q}%', f'%{q}%', f'%{q}%', limit))
    else:
        cur.execute('''
            SELECT "번호","날짜","종료날짜","날씨","작물","작업내용","사용기계","사용자재",COALESCE("작업목록",'') AS "작업목록","인력내역"
            FROM "작업일지"
            ORDER BY "날짜" DESC, "번호" DESC LIMIT %s
        ''', (limit,))
    rows = [dict(r) for r in cur.fetchall()]
    for r in rows:
        r['task_items'] = parse_task_list(r.get('작업목록', ''))
        r['인건비_표시'] = f"{compute_wage_from_detail(r.get('인력내역', '') or ''):,}원"
    cur.close()
    conn.close()
    return jsonify(rows)


@app.route('/api/materials')
def api_materials():
    conn = db_conn()
    cur = conn.cursor()
    cur.execute('SELECT "자재명","단위","가격","재고" FROM "자재" ORDER BY "자재명"')
    rows = [dict(r) for r in cur.fetchall()]
    cur.close()
    conn.close()
    return jsonify(rows)


@app.route('/api/options')
def api_options():
    conn = db_conn()
    cur = conn.cursor()
    opts = {}
    for tbl in ("옵션_날씨", "옵션_작물", "옵션_작업내용", "옵션_기계", "옵션_단위"):
        cur.execute(f'SELECT "항목" FROM "{tbl}" ORDER BY "항목"')
        opts[tbl] = [r['항목'] for r in cur.fetchall()]
    cur.close()
    conn.close()
    return jsonify(opts)


@app.route('/api/stats')
def api_stats():
    y = int(request.args.get('year', date.today().year))
    m = int(request.args.get('month', date.today().month))
    import calendar as _cal
    ms = date(y, m, 1).isoformat()
    me = date(y, m, _cal.monthrange(y, m)[1]).isoformat()
    if m >= SEASON_START_MONTH:
        ss = date(y, SEASON_START_MONTH, 1).isoformat()
        se = (date(y + 1, SEASON_START_MONTH, 1) - timedelta(days=1)).isoformat()
    else:
        ss = date(y - 1, SEASON_START_MONTH, 1).isoformat()
        se = (date(y, SEASON_START_MONTH, 1) - timedelta(days=1)).isoformat()
    conn = db_conn()
    cur = conn.cursor()
    def calc(s, e):
        cur.execute('SELECT COALESCE(SUM("인건비"),0) AS "합계", COUNT(*) AS "건수" FROM "작업일지" WHERE "날짜" BETWEEN %s AND %s', (s, e))
        r = cur.fetchone() or {}
        return {"인건비": r.get("합계", 0) or 0, "건수": r.get("건수", 0) or 0}
    month_stat = calc(ms, me)
    season_stat = calc(ss, se)
    cur.close()
    conn.close()
    return jsonify({"당월": month_stat, "시즌": season_stat})


@app.route('/api/calendar/<int:year>/<int:month>')
def api_calendar(year, month):
    import calendar as _cal
    month_start = date(year, month, 1)
    last_day = _cal.monthrange(year, month)[1]
    month_end = date(year, month, last_day)
    ms, me = month_start.isoformat(), month_end.isoformat()
    conn = db_conn()
    cur = conn.cursor()
    cur.execute('''
        SELECT "번호","날짜","종료날짜","작물","작업내용","날씨",COALESCE("작업목록",'') AS "작업목록"
        FROM "작업일지"
        WHERE "날짜" <= %s AND COALESCE("종료날짜","날짜") >= %s
        ORDER BY "날짜","번호"
    ''', (me, ms))
    rows = cur.fetchall()
    day_map = {}
    for row in rows:
        row = dict(row)
        try:
            sd = date.fromisoformat(row['날짜'])
            ed = date.fromisoformat(row['종료날짜']) if row.get('종료날짜') else sd
        except Exception:
            continue
        cur_d = max(sd, month_start)
        end_d = min(ed, month_end)
        while cur_d <= end_d:
            day_map.setdefault(str(cur_d.day), []).append(row)
            cur_d += timedelta(days=1)
    cur.close()
    conn.close()
    return jsonify({"year": year, "month": month, "days": last_day, "day_map": day_map})


HTML = '''<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>작업일지</title>
<style>
body{font-family:sans-serif;background:#f0f7f4;margin:0;padding:20px;color:#1b2e25}
.wrap{max-width:900px;margin:0 auto}
h1{font-size:28px;margin:0 0 16px;color:#2d6a4f}
input,button{font:inherit;padding:10px 12px}
button{cursor:pointer}
.row{display:flex;gap:8px;margin-bottom:16px}
#list .card{background:#fff;border-left:4px solid #74c69d;border-radius:12px;padding:14px;margin-bottom:10px;box-shadow:0 1px 6px rgba(0,0,0,.07)}
.muted{color:#6c757d;font-size:13px}
.err{color:#c62828;font-weight:700}
</style>
</head>
<body>
<div class="wrap">
  <h1>작업일지</h1>
  <div class="row">
    <input id="q" placeholder="검색어 입력" style="flex:1">
    <button onclick="loadWorks()">검색</button>
  </div>
  <div id="status">불러오는 중...</div>
  <div id="list"></div>
</div>
<script>
async function loadWorks(){
  const q = document.getElementById('q').value.trim();
  const status = document.getElementById('status');
  const list = document.getElementById('list');
  status.textContent = '불러오는 중...';
  list.innerHTML = '';
  try{
    const r = await fetch('/api/works?q=' + encodeURIComponent(q));
    const data = await r.json();
    if(!Array.isArray(data)){
      status.innerHTML = '<span class="err">응답 형식 오류</span>';
      return;
    }
    if(!data.length){
      status.textContent = '작업 내역이 없습니다.';
      return;
    }
    status.textContent = '';
    list.innerHTML = data.map(w => {
      const dateText = (w['종료날짜'] && w['종료날짜'] !== w['날짜']) ? `${w['날짜']} ~ ${w['종료날짜']}` : (w['날짜'] || '');
      return `<div class="card">
        <div><b>${w['작업내용'] || ''}</b></div>
        <div class="muted">날짜: ${dateText}</div>
        <div class="muted">작물: ${w['작물'] || '-'}</div>
        <div class="muted">날씨: ${w['날씨'] || '-'}</div>
        <div class="muted">기계: ${w['사용기계'] || '-'}</div>
        <div class="muted">자재: ${w['사용자재'] || '-'}</div>
      </div>`;
    }).join('');
  }catch(e){
    status.innerHTML = '<span class="err">초기화 오류: ' + e.message + '</span>';
  }
}
loadWorks();
</script>
</body>
</html>'''


@app.route('/')
def index():
    return render_template_string(HTML)


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
